<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="human-PC" name="Test" tests="4" failures="1" timestamp="18 Feb 2016 09:34:21 GMT" time="74.694" errors="0">
  <testcase name="loginByFireFox" time="10.738" classname="com.ctry.tests.Erp_login_1_loginFF"/>
  <testcase name="loginByDrivers" time="21.233" classname="com.ctry.tests.Erp_login_2_loginIE">
    <failure type="java.lang.AssertionError" message="异常 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: 异常 expected [true] but found [false]
	at com.ctry.tests.Erp_login_2_loginIE.loginByDrivers(Erp_login_2_loginIE.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- loginByDrivers -->
  <testcase name="loginByDrivers" time="7.262" classname="com.ctry.tests.Erp_login_2_loginIE"/>
  <testcase name="swichDishCategory" time="74.676" classname="com.ctry.tests.Erp_dish_3_switchDC"/>
</testsuite> <!-- Test -->
